// Code generated by MockGen. DO NOT EDIT.
// Source: grpc\pb\products\products_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=grpc\pb\products\products_grpc.pb.go -destination=grpc\pb\mock\products\client.go -package=mockproducts ProductsServiceClient
//

// Package mockproducts is a generated GoMock package.
package mockproducts

import (
	context "context"
	reflect "reflect"

	products "github.com/Nariett/arox-pkg/grpc/pb/products"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockProductsServiceClient is a mock of ProductsServiceClient interface.
type MockProductsServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockProductsServiceClientMockRecorder
	isgomock struct{}
}

// MockProductsServiceClientMockRecorder is the mock recorder for MockProductsServiceClient.
type MockProductsServiceClientMockRecorder struct {
	mock *MockProductsServiceClient
}

// NewMockProductsServiceClient creates a new mock instance.
func NewMockProductsServiceClient(ctrl *gomock.Controller) *MockProductsServiceClient {
	mock := &MockProductsServiceClient{ctrl: ctrl}
	mock.recorder = &MockProductsServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductsServiceClient) EXPECT() *MockProductsServiceClientMockRecorder {
	return m.recorder
}

// GetCategory mocks base method.
func (m *MockProductsServiceClient) GetCategory(ctx context.Context, in *products.GetCategoryRequest, opts ...grpc.CallOption) (*products.GetCategoryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCategory", varargs...)
	ret0, _ := ret[0].(*products.GetCategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategory indicates an expected call of GetCategory.
func (mr *MockProductsServiceClientMockRecorder) GetCategory(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategory", reflect.TypeOf((*MockProductsServiceClient)(nil).GetCategory), varargs...)
}

// GetProduct mocks base method.
func (m *MockProductsServiceClient) GetProduct(ctx context.Context, in *products.GetProductRequest, opts ...grpc.CallOption) (*products.GetProductResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProduct", varargs...)
	ret0, _ := ret[0].(*products.GetProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockProductsServiceClientMockRecorder) GetProduct(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockProductsServiceClient)(nil).GetProduct), varargs...)
}

// ListCategories mocks base method.
func (m *MockProductsServiceClient) ListCategories(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*products.ListCategoriesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListCategories", varargs...)
	ret0, _ := ret[0].(*products.ListCategoriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockProductsServiceClientMockRecorder) ListCategories(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockProductsServiceClient)(nil).ListCategories), varargs...)
}

// ListProducts mocks base method.
func (m *MockProductsServiceClient) ListProducts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*products.ListProductsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListProducts", varargs...)
	ret0, _ := ret[0].(*products.ListProductsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockProductsServiceClientMockRecorder) ListProducts(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockProductsServiceClient)(nil).ListProducts), varargs...)
}

// MockProductsServiceServer is a mock of ProductsServiceServer interface.
type MockProductsServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockProductsServiceServerMockRecorder
	isgomock struct{}
}

// MockProductsServiceServerMockRecorder is the mock recorder for MockProductsServiceServer.
type MockProductsServiceServerMockRecorder struct {
	mock *MockProductsServiceServer
}

// NewMockProductsServiceServer creates a new mock instance.
func NewMockProductsServiceServer(ctrl *gomock.Controller) *MockProductsServiceServer {
	mock := &MockProductsServiceServer{ctrl: ctrl}
	mock.recorder = &MockProductsServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductsServiceServer) EXPECT() *MockProductsServiceServerMockRecorder {
	return m.recorder
}

// GetCategory mocks base method.
func (m *MockProductsServiceServer) GetCategory(arg0 context.Context, arg1 *products.GetCategoryRequest) (*products.GetCategoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategory", arg0, arg1)
	ret0, _ := ret[0].(*products.GetCategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategory indicates an expected call of GetCategory.
func (mr *MockProductsServiceServerMockRecorder) GetCategory(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategory", reflect.TypeOf((*MockProductsServiceServer)(nil).GetCategory), arg0, arg1)
}

// GetProduct mocks base method.
func (m *MockProductsServiceServer) GetProduct(arg0 context.Context, arg1 *products.GetProductRequest) (*products.GetProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", arg0, arg1)
	ret0, _ := ret[0].(*products.GetProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockProductsServiceServerMockRecorder) GetProduct(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockProductsServiceServer)(nil).GetProduct), arg0, arg1)
}

// ListCategories mocks base method.
func (m *MockProductsServiceServer) ListCategories(arg0 context.Context, arg1 *emptypb.Empty) (*products.ListCategoriesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", arg0, arg1)
	ret0, _ := ret[0].(*products.ListCategoriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockProductsServiceServerMockRecorder) ListCategories(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockProductsServiceServer)(nil).ListCategories), arg0, arg1)
}

// ListProducts mocks base method.
func (m *MockProductsServiceServer) ListProducts(arg0 context.Context, arg1 *emptypb.Empty) (*products.ListProductsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", arg0, arg1)
	ret0, _ := ret[0].(*products.ListProductsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockProductsServiceServerMockRecorder) ListProducts(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockProductsServiceServer)(nil).ListProducts), arg0, arg1)
}

// mustEmbedUnimplementedProductsServiceServer mocks base method.
func (m *MockProductsServiceServer) mustEmbedUnimplementedProductsServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedProductsServiceServer")
}

// mustEmbedUnimplementedProductsServiceServer indicates an expected call of mustEmbedUnimplementedProductsServiceServer.
func (mr *MockProductsServiceServerMockRecorder) mustEmbedUnimplementedProductsServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedProductsServiceServer", reflect.TypeOf((*MockProductsServiceServer)(nil).mustEmbedUnimplementedProductsServiceServer))
}

// MockUnsafeProductsServiceServer is a mock of UnsafeProductsServiceServer interface.
type MockUnsafeProductsServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeProductsServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeProductsServiceServerMockRecorder is the mock recorder for MockUnsafeProductsServiceServer.
type MockUnsafeProductsServiceServerMockRecorder struct {
	mock *MockUnsafeProductsServiceServer
}

// NewMockUnsafeProductsServiceServer creates a new mock instance.
func NewMockUnsafeProductsServiceServer(ctrl *gomock.Controller) *MockUnsafeProductsServiceServer {
	mock := &MockUnsafeProductsServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeProductsServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeProductsServiceServer) EXPECT() *MockUnsafeProductsServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedProductsServiceServer mocks base method.
func (m *MockUnsafeProductsServiceServer) mustEmbedUnimplementedProductsServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedProductsServiceServer")
}

// mustEmbedUnimplementedProductsServiceServer indicates an expected call of mustEmbedUnimplementedProductsServiceServer.
func (mr *MockUnsafeProductsServiceServerMockRecorder) mustEmbedUnimplementedProductsServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedProductsServiceServer", reflect.TypeOf((*MockUnsafeProductsServiceServer)(nil).mustEmbedUnimplementedProductsServiceServer))
}
